using CompanionRobot.Core.Enums;
using CompanionRobot.Core.Events;
using CompanionRobot.Core.Interfaces;
using CompanionRobot.Core.Models;
using Microsoft.Extensions.Logging;

namespace CompanionRobot.Application.Services;

public sealed class AIOrchestrator(
    IMemoryService memoryService,
    IAIProvider aiProvider,
    IEventBus eventBus,
    IAppStateService appStateService,
    ILogger<AIOrchestrator> logger) : IAIOrchestrator
{
    private const int ContextWindowMessages = 12;

    public async Task<ChatMessage> GenerateAssistantMessageAsync(ChatMessage userMessage, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(userMessage);

        appStateService.SetBusy(true, "Generating response...");

        try
        {
            var request = new ChatRequest
            {
                UserInput = userMessage.Content,
                ContextMessages = memoryService.GetRecentContext(ContextWindowMessages),
                SessionId = memoryService.CurrentSession.Id.ToString()
            };

            logger.LogInformation("Sending request to AI provider {ProviderName} with {ContextCount} context messages.", aiProvider.ProviderName, request.ContextMessages.Count);
            var response = await aiProvider.GetResponseAsync(request, cancellationToken).ConfigureAwait(false);
            var assistantMessage = ChatMessage.Create(MessageRole.Assistant, response.Content, aiProvider.ProviderName);
            memoryService.AddMessage(assistantMessage);

            await eventBus.PublishAsync(new AIResponseGenerated(assistantMessage, response), cancellationToken).ConfigureAwait(false);
            appStateService.SetStatus($"Last response from {aiProvider.ProviderName} at {response.GeneratedAt.LocalDateTime:t}.");
            appStateService.SetWarning(response.IsFallbackResponse ? $"{aiProvider.ProviderName} used fallback behavior." : null);
            logger.LogInformation("AI response generated by {ProviderName}.", aiProvider.ProviderName);
            return assistantMessage;
        }
        catch (OperationCanceledException)
        {
            logger.LogWarning("AI response generation was canceled.");
            appStateService.SetWarning("Response generation canceled.");
            throw;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "AI orchestration failed.");
            appStateService.SetError(ex.Message);
            throw;
        }
        finally
        {
            appStateService.SetBusy(false);
        }
    }
}
