from pathlib import Path
p=Path('app/src/main/java/com/arenacommunity/control/MainActivity.java')
s=p.read_text()

def repl(src,sig,rep):
    i=src.find(sig)
    if i<0: raise SystemExit('missing '+sig)
    b=src.find('{',i);d=0;j=b
    while j<len(src):
        if src[j]=='{':d+=1
        elif src[j]=='}':
            d-=1
            if d==0:j+=1;break
        j+=1
    return src[:i]+rep+src[j:]

# imports / constants
s=s.replace('import java.util.regex.*;','import java.util.regex.*;\nimport javax.net.ssl.*;\nimport java.security.*;\nimport java.security.cert.*;\nimport org.json.*;')
s=s.replace('private static final String CHAT_RELAY="http://87.237.52.153:47831";','private static final String CHAT_RELAY="http://87.237.52.153:47831";\n  private static final String MOBILE_AC3="https://87.237.52.153:47832";\n  private static final String MOBILE_CERT_SHA256="6cf96e02a54520735b2a4c12567c82db75b61169734e7e3e2f53c051168fc387";')

load='''  private void loadControl(boolean startLoop){if(!ready())return;screen=Screen.SERVER;if(startLoop)stopLive();setBusy(true,"LOADING");io.submit(()->{try{ParsedControl pc;if(server.equals("AC3")){pc=loadMobileState();pc.chat=loadMobileChat();pc.console=loadMobileConsole();}else{String key=KEYS.get(server);HttpResult r=request("GET",BASE+"/control.php?server="+enc(key),null);ensureAdmin(r);pc=parseControl(r.body);}ParsedControl out=pc;runOnUiThread(()->{setBusy(false,"CONNECTED");renderControl(out);if(startLoop)startLive();});}catch(Exception e){runOnUiThread(()->{setBusy(false,authenticated?"CONNECTED":"OFFLINE");toast("Load failed: "+msg(e));});}});}'''
s=repl(s,'  private void loadControl(boolean startLoop)',load)

live='''  private void startLive(){stopLive();liveTask=timer.scheduleWithFixedDelay(()->{if(screen!=Screen.SERVER||!authenticated||destroyed)return;try{ParsedControl pc;if(server.equals("AC3")){pc=loadMobileState();pc.chat=loadMobileChat();pc.console=loadMobileConsole();}else{HttpResult r=request("GET",BASE+"/control.php?server="+enc(KEYS.get(server)),null);ensureAdmin(r);pc=parseControl(r.body);}ParsedControl out=pc;runOnUiThread(()->{if(screen==Screen.SERVER)renderControl(out);});}catch(Exception e){if(e.getMessage()!=null&&e.getMessage().contains("session"))sessionExpired();}},2,2,TimeUnit.SECONDS);}'''
s=repl(s,'  private void startLive()',live)

render='''  private void renderControl(ParsedControl pc){
    if(screen!=Screen.SERVER)return;title.setText("ARENA CONTROL");body.removeAllViews();
    LinearLayout tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);for(String ss:KEYS.keySet()){Button b=serverButton(ss,ss.equals(server));b.setOnClickListener(v->{server=ss;pane="chat";loadControl();});tabs.addView(b,new LinearLayout.LayoutParams(0,dp(62),1));}body.addView(tabs);
    LinearLayout map=card();map.addView(txt("CURRENT MAP",11,MUTED,true));TextView mn=txt("",22,Color.WHITE,true);mn.setText(TmnfText.render(pc.mapName.isEmpty()?"Unknown map":pc.mapName,Color.WHITE));map.addView(mn,lpTop(3));if(!pc.mapAuthor.isEmpty()){TextView au=txt("",12,MUTED,false);au.setText(new SpannableStringBuilder("by ").append(TmnfText.render(pc.mapAuthor,CYAN)));map.addView(au,lpTop(2));}String ts=pc.secondsLeft>=0?String.format(Locale.ROOT,"%02d:%02d",pc.secondsLeft/60,pc.secondsLeft%60):"--:--";map.addView(txt("● CONNECTED   ·   "+pc.playerCount+" online   ·   "+(pc.paused?"PAUSED":ts)+"   ·   live 2s",12,GREEN,true),lpTop(7));body.addView(map,lpTop(8));
    LinearLayout actions=card();actions.addView(txt("SESSION CONTROLS",12,Color.WHITE,true));
    LinearLayout r1=new LinearLayout(this);Button a1=blue("+1 min"),a5=blue("+5 min"),a10=blue("+10 min");a1.setOnClickListener(v->mobileAction("timer.add","","",60));a5.setOnClickListener(v->mobileAction("timer.add","","",300));a10.setOnClickListener(v->mobileAction("timer.add","","",600));r1.addView(a1,new LinearLayout.LayoutParams(0,dp(48),1));r1.addView(a5,new LinearLayout.LayoutParams(0,dp(48),1));r1.addView(a10,new LinearLayout.LayoutParams(0,dp(48),1));actions.addView(r1,lpTop(7));
    actions.addView(pair("PAUSE","timer.pause","RESUME","timer.resume"),lpTop(5));actions.addView(pair("PREVIOUS MAP","map.previous","SKIP MAP","map.skip"),lpTop(5));
    Button restart=blue("↻  RESTART MAP");restart.setOnClickListener(v->confirm("Restart current map?",()->mobileAction("map.restart","","",0)));actions.addView(restart,new LinearLayout.LayoutParams(-1,dp(48)));((LinearLayout.LayoutParams)restart.getLayoutParams()).topMargin=dp(5);
    Button erase=redButton("ERASE CURRENT MAP");erase.setOnClickListener(v->confirm("DELETE the current map from the server playlist? Arena records are kept.",()->mobileAction("map.erase","","",0)));actions.addView(erase,new LinearLayout.LayoutParams(-1,dp(48)));((LinearLayout.LayoutParams)erase.getLayoutParams()).topMargin=dp(5);
    actions.addView(pair("DISABLE VOTING","vote.disable","ENABLE VOTING","vote.enable"),lpTop(5));actions.addView(pair("CANCEL VOTE","vote.cancel","PASS VOTE","vote.pass"),lpTop(5));actions.addView(pair("DISABLE BETTING","bet.disable","ENABLE BETTING","bet.enable"),lpTop(5));Button cb=redButton("CANCEL BET + REFUND");cb.setOnClickListener(v->confirm("Cancel the active bet and refund it?",()->mobileAction("bet.cancel","","",0)));actions.addView(cb,new LinearLayout.LayoutParams(-1,dp(48)));((LinearLayout.LayoutParams)cb.getLayoutParams()).topMargin=dp(5);body.addView(actions,lpTop(8));
    LinearLayout live=card();LinearLayout tg=new LinearLayout(this);Button chat=segment("CHAT",pane.equals("chat")),con=segment("CONSOLE",pane.equals("console"));chat.setOnClickListener(v->{pane="chat";loadControl(false);});con.setOnClickListener(v->{pane="console";loadControl(false);});tg.addView(chat,new LinearLayout.LayoutParams(0,dp(42),1));tg.addView(con,new LinearLayout.LayoutParams(0,dp(42),1));live.addView(tg);if(pane.equals("chat"))renderChatPane(live,pc);else renderConsolePane(live,pc);body.addView(live,new LinearLayout.LayoutParams(-1,dp(360)));((LinearLayout.LayoutParams)live.getLayoutParams()).topMargin=dp(8);
    LinearLayout players=card();players.addView(txt("ONLINE PLAYERS ("+pc.players.size()+")",12,Color.WHITE,true));for(Player p:pc.players)players.addView(fullPlayerRow(p),lpTop(4));body.addView(players,lpTop(8));
  }'''
s=repl(s,'  private void renderControl(ParsedControl pc)',render)

chat='''  private void renderChatPane(LinearLayout live,ParsedControl pc){ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);live.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(pc.chat==null||pc.chat.isEmpty()){list.addView(txt(server.equals("AC3")?"Waiting for game chat…":"Direct chat addon is currently AC3 only.",12,MUTED,false));}else for(ChatLine m:pc.chat){TextView line=txt("",13,Color.WHITE,false);SpannableStringBuilder b=new SpannableStringBuilder();b.append(TmnfText.render(m.nickname.isEmpty()?m.login:m.nickname,CYAN));b.append("  ");b.append(TmnfText.render(m.message,Color.WHITE));line.setText(b);list.addView(line,lpTop(7));}LinearLayout send=new LinearLayout(this);EditText e=input("Send server message",false);Button b=blue("SEND");b.setOnClickListener(v->{String m=e.getText().toString().trim();if(!m.isEmpty()){mobileAction("chat.announce","",m,0);e.setText("");}});send.addView(e,new LinearLayout.LayoutParams(0,dp(46),1));send.addView(b,new LinearLayout.LayoutParams(dp(90),dp(46)));live.addView(send,lpTop(6));}'''
s=repl(s,'  private void renderChatPane(LinearLayout live,ParsedControl pc)',chat)

console='''  private void renderConsolePane(LinearLayout live,ParsedControl pc){ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);live.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(pc.console.isEmpty()){list.addView(txt("No recent console lines.",11,MUTED,false));return;}for(ConsoleLine x:pc.console){TextView l=txt(x.result,10,Color.rgb(203,220,230),false);l.setTypeface(Typeface.MONOSPACE);list.addView(l,lpTop(4));}}'''
s=repl(s,'  private void renderConsolePane(LinearLayout live,ParsedControl pc)',console)

submit='''  private void submit(String action,String target,String text,String minutes){if(server.equals("AC3")){int v=0;try{v=Integer.parseInt(minutes);}catch(Exception ignored){}mobileAction(action,target,text,v);return;}if(!ready())return;setBusy(true,"SENDING");io.submit(()->{try{String key=KEYS.get(server);HttpResult page=request("GET",BASE+"/control.php?server="+enc(key),null);ensureAdmin(page);String csrf=hidden(page.body,"csrf");if(csrf.isEmpty())throw new Exception("Control CSRF token not found");String reason=text,message="";if(action.equals("chat.announce")||action.equals("player.message")){message=text;reason=action.equals("player.message")?"Android app PM":"Android app";}String form="csrf="+enc(csrf)+"&server_key="+enc(key)+"&control_action="+enc(action)+"&target_login="+enc(target)+"&reason="+enc(reason)+"&message="+enc(message)+"&minutes="+enc(minutes);HttpResult r=request("POST",BASE+"/control.php?server="+enc(key),form);ensureAdmin(r);runOnUiThread(()->{setBusy(false,"CONNECTED");toast("Queued: "+action);if(screen==Screen.SERVER)loadControl(false);});}catch(Exception e){runOnUiThread(()->{setBusy(false,authenticated?"CONNECTED":"OFFLINE");toast("Action failed: "+msg(e));});}});}'''
s=repl(s,'  private void submit(String action,String target,String text,String minutes)',submit)

# Insert direct API helpers before refreshCurrent.
mark='  private void refreshCurrent(boolean user)'
helpers=r'''  private LinearLayout pair(String l1,String a1,String l2,String a2){LinearLayout r=new LinearLayout(this);Button b1=blue(l1),b2=blue(l2);b1.setOnClickListener(v->mobileAction(a1,"","",0));b2.setOnClickListener(v->mobileAction(a2,"","",0));r.addView(b1,new LinearLayout.LayoutParams(0,dp(48),1));r.addView(b2,new LinearLayout.LayoutParams(0,dp(48),1));return r;}
  private Button redButton(String s){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(null,Typeface.BOLD);b.setBackground(round(Color.rgb(177,43,43),1,Color.rgb(238,75,75),10));return b;}
  private void mobileAction(String action,String target,String text,int value){if(!server.equals("AC3")){toast("This direct control is staged on AC3 first.");return;}if(!ready())return;setBusy(true,"SENDING");io.submit(()->{try{JSONObject j=new JSONObject();j.put("action",action);j.put("actor",login);j.put("target",target==null?"":target);j.put("text",text==null?"":text);j.put("value",value);HttpResult r=mobileRequest("POST","/v1/action",j.toString());if(r.code!=200)throw new Exception("AC3 addon HTTP "+r.code+": "+r.body);JSONObject o=new JSONObject(r.body);if(!o.optBoolean("ok",false))throw new Exception(o.optString("error","Action rejected"));runOnUiThread(()->{setBusy(false,"CONNECTED");toast(o.optString("result","Done"));loadControl(false);});}catch(Exception e){runOnUiThread(()->{setBusy(false,"CONNECTED");toast("Action failed: "+msg(e));});}});}
  private ParsedControl loadMobileState()throws Exception{HttpResult r=mobileRequest("GET","/v1/state",null);if(r.code!=200)throw new Exception("AC3 addon HTTP "+r.code);JSONObject o=new JSONObject(r.body);ParsedControl p=new ParsedControl();JSONObject m=o.optJSONObject("map");if(m!=null){p.mapName=m.optString("name","");p.mapAuthor=m.optString("author","");}p.secondsLeft=o.optInt("seconds_left",-1);p.paused=o.optBoolean("paused",false);JSONArray a=o.optJSONArray("players");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;String lg=x.optString("login","");String nn=x.optString("nickname",lg);p.players.add(new Player(lg,TmnfText.plain(nn),"",x.optBoolean("spectator",false)));}p.playerCount=p.players.size();return p;}
  private List<ChatLine> loadMobileChat()throws Exception{HttpResult r=mobileRequest("GET","/v1/chat?limit=120",null);if(r.code!=200)throw new Exception("chat HTTP "+r.code);JSONArray a=new JSONArray(r.body);ArrayList<ChatLine> out=new ArrayList<>();for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;ChatLine c=new ChatLine();c.sourceKey="AC3";c.login=x.optString("login","");c.nickname=x.optString("nickname",c.login);c.message=x.optString("message","");out.add(c);}return out;}
  private ArrayList<ConsoleLine> loadMobileConsole()throws Exception{HttpResult r=mobileRequest("GET","/v1/console?lines=100",null);ArrayList<ConsoleLine> out=new ArrayList<>();if(r.code!=200)return out;JSONArray a=new JSONArray(r.body);for(int i=0;i<a.length();i++){ConsoleLine c=new ConsoleLine();c.result=a.optString(i,"");out.add(c);}return out;}
  private HttpResult mobileRequest(String method,String path,String body)throws Exception{HttpsURLConnection c=(HttpsURLConnection)new URL(MOBILE_AC3+path).openConnection();c.setSSLSocketFactory(pinnedFactory());c.setHostnameVerifier((h,s)->"87.237.52.153".equals(h));c.setConnectTimeout(5000);c.setReadTimeout(7000);c.setRequestProperty("User-Agent","ArenaControl-Android/2.5");c.setRequestProperty("Accept","application/json");c.setRequestProperty("X-Arena-Mobile","1");c.setRequestProperty("X-Arena-Login",login);c.setRequestProperty("Cookie",websiteCookie());if("POST".equals(method)){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");byte[] b=(body==null?"{}":body).getBytes(StandardCharsets.UTF_8);try(OutputStream o=c.getOutputStream()){o.write(b);}}int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String txt=in==null?"":new String(readAll(in),StandardCharsets.UTF_8);return new HttpResult(code,c.getURL().toString(),txt);}
  private String websiteCookie(){StringBuilder b=new StringBuilder();for(HttpCookie c:cookies.getCookieStore().getCookies()){if(b.length()>0)b.append("; ");b.append(c.getName()).append("=").append(c.getValue());}return b.toString();}
  private SSLSocketFactory pinnedFactory()throws Exception{TrustManager[] t={new X509TrustManager(){public X509Certificate[] getAcceptedIssuers(){return new X509Certificate[0];}public void checkClientTrusted(X509Certificate[] c,String a)throws CertificateException{}public void checkServerTrusted(X509Certificate[] chain,String auth)throws CertificateException{if(chain==null||chain.length==0)throw new CertificateException("No certificate");try{MessageDigest md=MessageDigest.getInstance("SHA-256");StringBuilder h=new StringBuilder();for(byte x:md.digest(chain[0].getEncoded()))h.append(String.format(Locale.ROOT,"%02x",x));if(!h.toString().equals(MOBILE_CERT_SHA256))throw new CertificateException("AC3 mobile certificate mismatch");}catch(CertificateException e){throw e;}catch(Exception e){throw new CertificateException(e);}}}};SSLContext sc=SSLContext.getInstance("TLS");sc.init(null,t,new SecureRandom());return sc.getSocketFactory();}

'''
if mark not in s:raise SystemExit('refresh marker missing')
s=s.replace(mark,helpers+mark,1)

# extend ParsedControl
s=s.replace('static class ParsedControl{String mapName="",mapAuthor="",chatError="";int playerCount=0;ArrayList<Player> players=new ArrayList<>();ArrayList<ConsoleLine> console=new ArrayList<>();List<ChatLine> chat=new ArrayList<>();}', 'static class ParsedControl{String mapName="",mapAuthor="",chatError="";int playerCount=0,secondsLeft=-1;boolean paused=false;ArrayList<Player> players=new ArrayList<>();ArrayList<ConsoleLine> console=new ArrayList<>();List<ChatLine> chat=new ArrayList<>();}')
p.write_text(s)
print('v2.5 AC3 direct transport applied')
